version: '3.9'
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $WSL_SRC:$DOCKER_SRC
    working_dir: $DOCKER_SRC
    command: sh -c "cd react-sample && yarn start"
    ports:
      - $WSL_PORT:$DOCKER_PORT
    tty: true
    stdin_open: true